config/routes.rb
CheckUp::Application.routes.draw do
  devise_for :users

  get   '/routines/get_event', to: 'events#show',    as: 'event_show'
  post  '/routines/tag_event', to: 'tags#tag_event', as: 'tag_event'

  patch '/setup/tag',          to: 'tags#update',       as: 'update_tag'
  post  '/setup/tag',          to: 'tags#create',       as: 'new_tag'
  patch '/setup/category',     to: 'categories#update', as: 'update_category'
  post  '/setup/category',     to: 'categories#create', as: 'new_category'
  patch '/setup/save_routine', to: 'tags#save_routine', as: 'save_routine'

  get '/setup/color', to: 'pages#get_color',  as: 'get_color'
  get '/setup',    to: 'pages#setup_page',    as: 'setup'
  get '/events',   to: 'pages#events_page',   as: 'events', defaults: { events: true }
  get '/routines', to: 'pages#routines_page', as: 'routines'
  root 'static_pages#home'
end

app/views/layouts/_event_jquery_date_form.html.erb
<div id="cal-1" class="input-group date">
  <input type="text" id="from" name="from" placeholder="From" readonly="true" style="color:black">
</div>
<div id="cal-2" class="input-group date">
  <input type="text" id="to" name="to" placeholder="To" readonly="true" style="color:black">
</div>

<script>
  $(function() {
    var userDate = "<%= @create_date %>".split(" ")[0].split('-'),
        userDay = userDate[1] + '/' + userDate[2] + '/' + userDate[0]
    $("#single-trace").attr("data-user-create", userDay)
    $( "#from" ).datepicker({
      maxDate: -1,
      minDate: userDay,
      showOtherMonths: true,
      selectOtherMonths: true,
      showOn: "both",
      buttonImage: "<%= asset_path('calendar.gif') %>",
      buttonImageOnly: true,
      autoclose: true,
      onClose: function( selectedDate ) {
        var dayArray = selectedDate.split('/');
        var day = dayArray[0] + '/' + (parseInt(dayArray[1]) + 1) + '/' + dayArray[2];
        $( "#to" ).datepicker( "option", "minDate", day );
        $( "#to" ).datepicker( "option", "defaultDate", selectedDate);
      }
    });
    $( "#to" ).datepicker({
      maxDate: -1,
      showOn: "both",
      minDate: userDay,
      showOtherMonths: true,
      selectOtherMonths: true,
      buttonImage: "<%= asset_path('calendar.gif') %>",
      buttonImageOnly: true,
      autoclose: true,
      onClose: function( selectedDate ) {
        var dayArray = selectedDate.split('/');
        var day = dayArray[0] + '/' + (parseInt(dayArray[1]) - 1) + '/' + dayArray[2];
        $( "#from" ).datepicker( "option", "maxDate", day );
      }
    });
  });
</script>

app/views/layouts/_nav_bar.html.erb
<nav>
  <ul class="nav-ul">
    <li><%= link_to "Setup", setup_path %></li>
    <li><%= link_to "Routines", routines_path %></li>
    <li><%= link_to "Events", events_path %></li>
    <li><%= render 'layouts/user_login_widget' %></li>
  </ul>
</nav>

app/views/layouts/_user_login_widget.html.erb
<% if user_signed_in? %>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Login', new_user_session_path %> / <%= link_to 'Sign Up', new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CheckUp</title>
  <meta property="og:image" content="<%= image_url('checkup-og.png') %>">
  <meta property="og:site_name", content="CheckUp">
  <meta property="og:description", content="Lightweight mobile metrics to see where you spend your time each day.">
  <meta property="og:title", content="CheckUp">
  <meta property="og:url", content="http://checkupapp.herokuapp.com">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body data-controller="<%= controller.controller_path %>"
  data-action="<%= controller.action_name %>">
  <div class="nav-bar"><%= render 'layouts/nav_bar' %></div>
  <div class="messages">
    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>